#!/bin/sh

PATH=/command:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin

cmdline=$(awk '{print $(NF)}' /proc/cmdline)

if [ -d /etc/runit/runsvdir/$cmdline ];then
  default=$cmdline
else
  default=default
fi
if [ "$default" == "single" ];then
  rc.single
else
  rc.multi
fi
runsvchdir $default

exec env - PATH=$PATH \
runsvdir -P /service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
