#!/bin/sh
exec 2>&1

PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin

LAST=0
test -x /etc/runit/reboot && LAST=6

echo 'Waiting for services to stop...'
sv -w19 force-stop /etc/runit/runsvdir/current/*
sv exit /etc/runit/runsvdir/current/*

echo 'Shutdown...'
export RUNLEVEL=$LAST
/etc/rc.shutdown $LAST
