post_install() {
  cp /sbin/init /sbin/init.sysv
  ln -s /sbin/runit-init /sbin/init
  ln -sf /etc/runit/runsvdir/runit-run-default /etc/runit/runsvdir/default
  runsvchdir default
  ln -s /etc/runit/runsvdir/current /service
  echo "Runit-run is installed, restart with
        /sbin/init.sysv 6" 
}

post_remove() {
  [ -L /sbin/init ] && [ -f /sbin/init.sysv ] && rm /sbin/init && mv /sbin/init.sysv /sbin/init
}

# vim:set ts=2 sw=2 et:
