#!/bin/sh -e
tty=tty${1}
if [ -d /etc/sv/agetty-${tty} ];then
  echo "This tty already exists"
  exit 1
fi
mkdir /etc/sv/agetty-${tty}
ln -s /etc/sv/agetty-generic/run /etc/sv/agetty-${tty}/
ln -s /etc/sv/agetty-generic/finish /etc/sv/agetty-${tty}/
