#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
MSG="System is going down in 14 seconds..."

#echo 'disabled.' ; exit
touch /etc/runit/stopit
chmod 0100 /etc/runit/stopit && \
  echo "$MSG" | wall
exec sleep 14
